<?php
declare(strict_types=1);

return [
    'site_name' => 'SNAPVERE',
    'version' => '0.1.22',
    'admin_email' => 'info@brendigo.com',
    'mail_from' => 'no-reply@snapvere.com',
    'token_ttl' => 900,
    'lead_retention_days' => 90,
    'counter_baseline' => 1795,
    'rate_limit' => [
        'window_seconds' => 900,
        'max_attempts' => 20,
    ],
    'allowed_origins' => [
        'https://snapvere.com',
        'https://www.snapvere.com',
        'https://download.snapvere.com',
    ],
    'require_origin_for_post' => true,
    'blocked_email_domains' => [
        '10minutemail.com',
        '10minutemail.net',
        '20minutemail.com',
        '33mail.com',
        'dispostable.com',
        'emailondeck.com',
        'fakeinbox.com',
        'getnada.com',
        'guerrillamail.com',
        'guerrillamail.net',
        'guerrillamail.org',
        'maildrop.cc',
        'mailinator.com',
        'mailnesia.com',
        'mintemail.com',
        'mohmal.com',
        'sharklasers.com',
        'temp-mail.org',
        'tempail.com',
        'tempmail.com',
        'tempmail.net',
        'throwawaymail.com',
        'trashmail.com',
        'yopmail.com',
    ],
    'packages' => [
        'windows-setup' => [
            'label_en' => 'Windows Setup',
            'label_hr' => 'Windows instalacija',
            'file' => 'SNAPVERE-Setup.exe',
            'mime' => 'application/vnd.microsoft.portable-executable',
            'size' => 336526148,
            'sha256' => 'dd08c51953908d43adc2b19357eec2f8ef0b245c3007b4cb7fe36c4a893eeb03',
            'group' => 'windows',
        ],
        'windows-portable' => [
            'label_en' => 'Windows Portable',
            'label_hr' => 'Windows Portable',
            'file' => 'SNAPVERE-Portable.exe',
            'mime' => 'application/vnd.microsoft.portable-executable',
            'size' => 336676694,
            'sha256' => '2866c1a558c1e19aa2329d0c63e4ffff04f5c713cba91ca6a4e9d3c1bcc67db6',
            'group' => 'windows',
        ],
        'chrome' => [
            'label_en' => 'Chrome extension',
            'label_hr' => 'Chrome ekstenzija',
            'file' => 'SNAPVERE-Chrome.zip',
            'mime' => 'application/zip',
            'size' => 36483,
            'sha256' => 'c407445edc4db71394488391a60e482b8996d1a0250b56b01e25cd83021cadd6',
            'group' => 'browser',
        ],
        'edge' => [
            'label_en' => 'Edge extension',
            'label_hr' => 'Edge ekstenzija',
            'file' => 'SNAPVERE-Edge.zip',
            'mime' => 'application/zip',
            'size' => 36483,
            'sha256' => 'c407445edc4db71394488391a60e482b8996d1a0250b56b01e25cd83021cadd6',
            'group' => 'browser',
        ],
        'firefox' => [
            'label_en' => 'Firefox extension',
            'label_hr' => 'Firefox ekstenzija',
            'file' => 'SNAPVERE-Firefox.zip',
            'mime' => 'application/zip',
            'size' => 36544,
            'sha256' => 'aff90d56bcd3ddc01d334e003f94dcd64022bf6905cedefb59d758da835cb3c9',
            'group' => 'browser',
        ],
        'opera' => [
            'label_en' => 'Opera extension',
            'label_hr' => 'Opera ekstenzija',
            'file' => 'SNAPVERE-Opera.zip',
            'mime' => 'application/zip',
            'size' => 36483,
            'sha256' => 'c407445edc4db71394488391a60e482b8996d1a0250b56b01e25cd83021cadd6',
            'group' => 'browser',
        ],
    ],
];
