<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>SNAPVERE-Demo</AssemblyName>
    <RootNamespace>Snapvere.Demo</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>x86;x64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Snapvere.Packaging\Snapvere.Packaging.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(SnapverePayloadX86Path)' != '' and Exists('$(SnapverePayloadX86Path)')">
    <EmbeddedResource Include="$(SnapverePayloadX86Path)" LogicalName="Snapvere.Payload.x86.zip" />
  </ItemGroup>
  <ItemGroup Condition="'$(SnapverePayloadX64Path)' != '' and Exists('$(SnapverePayloadX64Path)')">
    <EmbeddedResource Include="$(SnapverePayloadX64Path)" LogicalName="Snapvere.Payload.x64.zip" />
  </ItemGroup>
  <ItemGroup Condition="'$(SnapverePayloadArm64Path)' != '' and Exists('$(SnapverePayloadArm64Path)')">
    <EmbeddedResource Include="$(SnapverePayloadArm64Path)" LogicalName="Snapvere.Payload.arm64.zip" />
  </ItemGroup>
</Project>
