<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Snapvere.Capture</AssemblyName>
    <RootNamespace>Snapvere.Capture</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Snapvere.Domain\Snapvere.Domain.csproj" />
    <ProjectReference Include="..\Snapvere.Shared\Snapvere.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Graphics.Win2D" />
  </ItemGroup>
</Project>
