<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <AssemblyName>Snapvere.UnitTests</AssemblyName>
    <RootNamespace>Snapvere.UnitTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Snapvere.Application\Snapvere.Application.csproj" />
    <ProjectReference Include="..\..\src\Snapvere.Capture\Snapvere.Capture.csproj" />
    <ProjectReference Include="..\..\src\Snapvere.Domain\Snapvere.Domain.csproj" />
    <ProjectReference Include="..\..\src\Snapvere.Imaging\Snapvere.Imaging.csproj" />
    <ProjectReference Include="..\..\src\Snapvere.Packaging\Snapvere.Packaging.csproj" />
  </ItemGroup>
</Project>
